### ISSUE TITLE
Error in control "No outside collaborators should have access in each private repository":  pq: missing FROM-clause entry for table "r"

### ISSUE THREAD

**Issue by Taytay** [turbot/steampipe-mod-github-sherlock#5]
**Describe the bug**
Error when running this check: `No outside collaborators should have access in each private repository`

```
| + No outside collaborators should have access in each private repository ......................   1 /   1 [=         ]
| | |
| | ERROR: pq: missing FROM-clause entry for table "r"
```

**Steampipe version (`steampipe -v`)**
Example: v0.5.1

**Plugin version (`steampipe plugin list`)**
Github plugin:
` hub.steampipe.io/plugins/turbot/github@latest       | 0.5.0   | github`
I'm at commit 911402c of this particular repo

**To reproduce**
I just ran all checks:
`steampipe check all`

**Expected behavior**
No error message.

**Additional context**
Here is the code of the control that's failing:
https://github.com/turbot/steampipe-mod-github-sherlock/blob/911402ce8bfbf5de5c458f201d095a79f55908f4/controls/private_repo.sp#L57-L74

**Comment by e-gineer** [comment]
Thanks @Taytay for the bug report!

Small fix to remove the errant `r.` on line #72. Please pull the latest on main and try again.
